### ISSUE TITLE
Text input lags

### ISSUE THREAD

**Issue by AgentFire** [Art-Stea1th/Enhanced-Syntax-Highlighting#18] opened 2019-06-29 13:22 UTC
If the extension is installed and enabled, then coding on my VS2019 Community turns into a half nightmare.

If I type code text in a code window on my keyboard faster than 1 symbol per second, then the VS hangs right until it reaches that 1 symbol/sec speed, it hangs after rendering each new character input.

Using ctrl-z to undo has the same effect. It seems that any text-change event on the code window produces massive hang for around 1 second, on my Core i5 processor.

If the extension is disabled, then everything works fine and smooth, so there.

**Comment by ericbyrd** [comment] 2019-09-13 13:58
Having the same issue. VS 2019 16.2.5.

**Comment by Art-Stea1th** [comment] 2019-09-16 17:52
This is a duplicate of the #10 issue. This issue is known and already quite old. I would be grateful if you can offer a solution.

Thanks.

**Closed as completed by Art-Stea1th** 2019-09-16 17:52 UTC
Labels: duplicate
